# Generated by Django 4.0.5 on 2022-06-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='picture',
        ),
    ]
